### ISSUE TITLE
Fatal error in Typo3 8.7.4

### ISSUE THREAD

**Issue by elrosi** [xperseguers/t3ext-tscobj#12]
After installing, the following error is displayed: 
Fatal error: Class 'Causal\Tscobj\Controller\Pi1\Pi1Controller' not found in /storage/vhost/netsuccess/sub/netsuccess_devel/devel.netsuccess.sk/cba/typo3conf/ext/tscobj/ext_localconf.php on line 11

**Comment by simonschaufi** [comment]
Please help us to finish the extension for TYPO3 8: https://github.com/xperseguers/t3ext-tscobj/pull/15
