### ISSUE TITLE
Any update for TYPO3 v9.5?

### ISSUE THREAD

**Issue by DavidBruchmann** [xperseguers/t3ext-tscobj#14]
An update for TYPO3 9.5 would be cool. Is there anything planned?

**Comment by xperseguers** [comment]
If you have a look into the comment https://extensions.typo3.org/extension/tscobj/ and the activity on this repository, you'll see that there is probably nothing planned...

But PR are always welcome.

**Comment by simonschaufi** [comment]
I have patched the extension and made it ready for TYPO3 8 but I wasn't able to get the wizard finished.

**Comment by christophlehmann** [comment]
As of last TER version comment the wizard is deprecated (and is not really necessary)

**Comment by xperseguers** [comment]
It was marked as deprecated in order to be able to release a new version because I had absolutely no time to invest into making it work again. Once you remove the wizard, there's not much anymore in this extension :)

**Comment by DavidBruchmann** [comment]
@simonschaufi than's had a look already but willl test (and adjust) ASAP

**Comment by zzzooorrrx** [comment]
@DavidBruchmann Is there a working version of tscobj for v9.5? Or any other solution?

**Comment by simonschaufi** [comment]
@zzzooorrrx Right now there is no compatible version but is of course another solution which is simply to write an Extension. Financial support is highly appreciated to make this extension compatible with latest TYPO3 versions ;)

**Comment by DavidBruchmann** [comment]
@zzzooorrrx currently not, but in fluid-templates it's always possible to include cObjects, so the emergency might not so strong like in other template-types.
Like Simon stated: Financial support is highly appreciated, then I had the option to dig deeper in it too.

**Comment by simonschaufi** [comment]
@DavidBruchmann @zzzooorrrx I just released version 1.0.0 which is fully compatible with TYPO3 8. Does anyone wants to support me making it also compatible with TYPO3 9 and even 10? Sponsor me on Github or via Paypal with the link over there: https://extensions.typo3.org/extension/tscobj

**Comment by lthurston** [comment]
If you're in a pinch, I think the current version of plugin works to some degree with version 9 after making a tiny change. I haven't tested the wizard in the backend, but here's a fork with that teensy commit: https://github.com/lthurston/t3ext-tscobj

I think that the frontend rendering could be simplified with the user of the f:cObject VH in the next version.

**Comment by simonschaufi** [comment]
@lthurston I wanted to motivate people to sponsor further development.

I had a look at the fork but couln't find the commit, neither in master, nor in any other branches.

**Comment by lthurston** [comment]
Ooops, something went wrong. Namely, I forgot to push to my fork. Done now.

I hope I'm not preventing sponsorship. I just wanted to help anyone who might be in a tough situation--like I thought I was trying to upgrade a TYPO3 site to version 9--get a quick fix in place. There definitely more to be done.

**Comment by simonschaufi** [comment]
ok, I see it now. But generally speaking, making changes in master is not a good idea. Always create a separate branch for your changes!

**Comment by lthurston** [comment]
Thanks for the tip. This isn't a PR, however, and may not become one. It's just a friendly "how do you do?" and "hope this works."

**Comment by stephangrass** [comment]
Hi Simon,
I like to sponsor to make tscobj compatible to 9 or 10. Indeed there are still other solutions, but I use and like your extension until first upload.
How much money do you still need to do so?

Stephan

**Comment by simonschaufi** [comment]
Hi Stephan, thank you very much for offering some sponsoring! My goal is to reach 1500€. You can either make a one time donation via paypal or monthly support via Github. Thank you :green_heart:

**Comment by stephangrass** [comment]
Ok. I contributed my little part to it ...

**Comment by simonschaufi** [comment]
@lthurston @DavidBruchmann I wanted to ask you if you also would like to support my work on this extension. I got some support from Stephan already which I really appreciate but wanted to ask you as well before I release a new release.

**Comment by DavidBruchmann** [comment]
@simonschaufi  Need some sponsoring on any extension or any kind of project by myself as we've a very hard time to survive currently. So "would like" is a question that is out of reach for us. Sorry.

**Comment by simonschaufi** [comment]
Updated the extension even up to v11
