### ISSUE TITLE
Fatal error since upgrade to 1.0.1 / Typo3 8.7.30

### ISSUE THREAD

**Issue by baden32** [xperseguers/t3ext-tscobj#17]
Intégration of tscobj on Typo3 8.7.30 was working fine but since I installed 1.0.1 I get general error.
On FE
Oops, an error occurred!
syntax error, unexpected '=' 

On BE (when I click on see TS hierarchy button):
	
Oops, an error occurred!
Return value of Causal\Tscobj\Controller\Wizard\TypoScriptBrowser::init() must be an instance of Causal\Tscobj\Controller\Wizard\void, none returned

the TS included "tmp.test" is very simple
tmp.test = TEXT
tmp.test.value = HELLO

If tscobj 0.3 is installed, everything is workijng fine, I get the errors as soon as 1.0.1 (or 1.0) is activated.
Am I doing soemthing wrong here?
Thank you in advance for your help.
Regards

**Comment by simonschaufi** [comment]
Sounds like you have a really old PHP Version. Could you update to PHP 7.2?

**Comment by baden32** [comment]
We are currently running PHP 7.0.33 so, sounds like we need to upgrade to 7.2?

**Comment by xperseguers** [comment]
Yes, since PHP 7.0 is not supported anymore anyway: https://www.php.net/supported-versions.php
