### ISSUE TITLE
Typo3 7.x

### ISSUE THREAD

**Issue by HamburgerJungeJr** [xperseguers/t3ext-tscobj#4]
Hi
is there any support for Typo3 7.x planned?

**Comment by xperseguers** [comment]
Hi, I started making it compatible. Feel free to open tickets with specific problems you face or to contribute, currently investing little time to it since no real need for 7.x for my customers currently.

**Comment by wimr0001** [comment]
In Typo3 7.6, Frontend, I encounter the error class "tslib_pibase" not found in class.tx_tscobj_pi1.php on line 45.
In the ext_emconf.php is set "'typo3' => '4.5.0-7.6.99', so there was no warning at installing the extension.
Any idea when the extension is adjusted to typo3 7.6?
