### ISSUE TITLE
passing parameters to class function

### ISSUE THREAD

**Issue by derBoogie** [xperseguers/t3ext-tscobj#6]
Hey Xavier,

It would be great if there was an opportunity to pass parameters to a userFunc, like this:

lib.myLib = USER
lib.myLib.userFunc = MyClass->main

With your plugin I can call lib.myLib, but I can't pass any parameters to.

Greetinngs TJ

**Comment by simonschaufi** [comment]
@derBoogie is this still valid?

**Comment by simonschaufi** [comment]
No response.
